### ISSUE TITLE
Clean apk cache

### ISSUE THREAD

**Issue by jangaraj** [frol/docker-alpine-glibc#22] opened 2018-07-07 00:02 UTC
Could you delete apk cache (`rm -rf /var/cache/apk/*`), please? 
alpine:3.8 doesn't have any cached files, so we can save 1.2MB:
```
$ docker run --rm -ti alpine:3.8 ls -lah /var/cache/apk
total 0
drwxr-xr-x    2 root     root           6 Jul  5 14:47 .
drwxr-xr-x    4 root     root          29 Jul  5 14:47 ..
$ docker run --rm -ti frolvlad/alpine-glibc:alpine-3.8 ls -lah /var/cache/apk
total 1244
drwxr-xr-x    2 root     root          70 Jul  6 18:02 .
drwxr-xr-x    5 root     root          45 Jul  6 18:02 ..
-rw-r--r--    1 root     root      730.6K Jul  6 18:02 APKINDEX.adfa7ceb.tar.gz
-rw-r--r--    1 root     root      512.0K Jul  6 18:02 APKINDEX.efaa1f73.tar.gz
$ docker run --rm -ti frolvlad/alpine-glibc:alpine-3.8 du -sh /var/cache/apk
1.2M    /var/cache/apk
```
Thank you.

**Comment by frol** [comment] 2018-07-07 06:45
Good catch... It seems that `apk del` changed its behavior and requires the packages list now, so I have to use `apk del --no-cache` everywhere...

**Comment by frol** [comment] 2018-07-07 12:05
I figured I would start with a question to the Alpine community since it is sort of a regression in the behavior: https://bugs.alpinelinux.org/issues/9063

**Comment by frol** [comment] 2018-07-23 16:18
FYI, Timo Teräs (as listed on Redmine) has [fixed the issue in apk](https://git.alpinelinux.org/cgit/apk-tools/commit/?id=e1a05c74cb8ae6ab41ee960343cc64a0a9af95a5) and it seems that we only need to wait for a new apk release.

**Comment by nikolay** [comment] 2018-07-25 14:17
Thanks for taking the initiative on this, @frol!

**Comment by nikolay** [comment] 2019-02-04 16:59
@frol Maybe you should close the issue now.

**Closed** 2019-02-11 19:43 UTC
