### ISSUE TITLE
docker-alpine-glibc for arm64

### ISSUE THREAD

**Issue by Denusdv** [frol/docker-alpine-glibc#25] opened 2018-10-20 07:39 UTC
Hi guys
I'm wondering if you have tried to build the same image for ARM64 arch, is there any plan to support other platforms. I'm struggling to build such image by my own, unfortunately, have limited knowledge base on the Linux realm as a JAVA developer.

**Comment by frol** [comment] 2018-10-20 11:08
It is a duplicate of #23. Please, give https://github.com/chrisanthropic/docker-alpine-rpi-glibc a try.

**Closed by frol** 2018-10-20 11:08 UTC
